name = "Recommender"
uuid = "f1dcbcfb-0b1d-45c0-883e-2edcfc1d4c23"
authors = ["yng87 <k.yanagi07@gmail.com> and contributors"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
